name: Build (Linux)

on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ${{ matrix.runner.os }}
        strategy:
            matrix:
                runner:
                - os: ubuntu-latest
                  arch: "x86_64"
                - os: ubuntu-24.04-arm
                  arch: "arm64"

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
                submodules: true

          - name: Cache dependencies
            uses: actions/cache@v4
            with:
                path: third_party
                key: ${{ runner.os }}-${{ matrix.runner.arch }}-deps-${{ hashFiles('build-deps.sh') }}

          - name: Install dependencies
            run: |
                sudo apt update
                sudo apt install -y $(cat tools/requirements-ubuntu.txt)
                ./build-deps.sh
            shell: bash

          - name: Build for Linux (${{ matrix.runner.arch }})
            run: |
                set -o pipefail
                CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release
                cmake --build build --parallel $(nproc) 2>&1 | tee build.log
            shell: bash

          - name: Package Linux (${{ matrix.runner.arch }}) PR artifact
            if: github.event_name == 'pull_request'
            run: |
                set -euo pipefail
                cpack -G TGZ --config build/CPackConfig.cmake

                TGZ_PATH="$(find . -maxdepth 1 -type f -name '*.tar.gz' | head -n 1)"
                if [ -z "${TGZ_PATH}" ]; then
                  echo "No .tar.gz package found in build/"
                  exit 1
                fi

                PR_NUM="${{ github.event.pull_request.number }}"
                TGZ_NAME="3SX-pr-${PR_NUM}-linux-${{ matrix.runner.arch }}.tar.gz"
                mv "${TGZ_PATH}" "${TGZ_NAME}"
            shell: bash

          - name: Upload Linux (${{ matrix.runner.arch }}) PR artifact
            if: github.event_name == 'pull_request'
            uses: actions/upload-artifact@v4
            with:
                name: 3SX-pr-${{ github.event.pull_request.number }}-linux-${{ matrix.runner.arch }}
                path: 3SX-pr-${{ github.event.pull_request.number }}-linux-${{ matrix.runner.arch }}.tar.gz

          - name: Upload Linux (${{ matrix.runner.arch }}) build log
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: build-log-linux-${{ matrix.runner.arch }}
                path: build.log
